INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('CHARMHANDER','2020-02-08',0,FALSE,-11);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('PLANTMON','2021-11-15',2,TRUE,-5.7);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('SQUIRTLE','1993-04-02',3,FALSE,-12.13);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('ANGEMON','2005-06-12',1,TRUE,-45);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('BOARMON','2005-06-07',7,TRUE,20);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('BLOSSOM','1998-10-13',3,TRUE,17);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('DITTO','2022-05-14',4,TRUE,22);