INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('AGUMON','2020-02-03',0,TRUE,10.23);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('GABUMON','2018-11-15',2,TRUE,8);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('PIKACHU','2021-01-07',1,FALSE,15.04);

INSERT INTO ANIMALS(NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG)
VALUES('DEVIMON','2017-05-12',5,TRUE,11);