-- SELECT FROM ANIMALS WHERE NAME LIKE '%MON%';
-- SELECT NAME FROM ANIMALS WHERE DATE_OF_BIRTH::DATE >= '2016-01-01' AND DATE_OF_BIRTH::DATE <='2019-12-31';
-- SELECT NAME FROM ANIMALS WHERE NEUTERED = TRUE AND  ESCAPE_ATTEMPTS < 3;
-- SELECT DATE_OF_BIRTH FROM ANIMALS WHERE NAME='AGUMON' OR NAME= 'PIKACHU';
-- SELECT NAME, ESCAPE_ATTEMPTS FROM ANIMALS WHERE WEIGHT_KG > 10.5;
-- SELECT * FROM ANIMALS WHERE NEUTERED = TRUE;
-- SELECT * FROM ANIMALS WHERE NAME <> 'Gabumon';
-- SELECT * FROM ANIMALS WHERE WEIGHT_KG >=10.4 OR WEIGHT_KG <= 17.3;
BEGIN TRANSACTION;
 UPDATE ANIMALS
 SET SPECIES = 'UNSPECIFIED';
UPDATE ANIMALS
SET SPECIES = 'DIGIMON' WHERE NAME LIKE '%MON';
 UPDATE ANIMALS
 SET SPECIES = 'POKEMON' WHERE SPECIES LIKE 'UNSPECIFIED';
 COMMIT;
 BEGIN TRANSACTION;
 DELETE FROM ANIMALS;
 ROLLBACK;
 BEGIN TRANSACTION;
  DELETE FROM ANIMALS WHERE DATE_OF_BIRTH > DATE'2022-01-01';
  SAVEPOINT SP1;
  UPDATE ANIMALS
SET WEIGHT_KG = (WEIGHT_KG * -1);
ROLLBACK TO SP1;
UPDATE ANIMALS
SET WEIGHT_KG = (WEIGHT_KG * -1) WHERE WEIGHT_KG < 0;
COMMIT;
SELECT COUNT(*) FROM ANIMALS;
SELECT COUNT(*) FROM ANIMALS WHERE ESCAPE_ATTEMPTS <= 0;
SELECT AVG(WEIGHT_KG) FROM ANIMALS;
SELECT NEUTERED, SUM(ESCAPE_ATTEMPTS) AS ATTEMPTS FROM ANIMALS GROUP BY NEUTERED;
SELECT NAME, MIN(WEIGHT_KG) AS MIN_WEIGHT, MAX(WEIGHT_KG) AS MAX_WEIGHT FROM ANIMALS GROUP BY NAME;
SELECT NAME, AVG(ESCAPE_ATTEMPTS) FROM ANIMALS WHERE DATE_OF_BIRTH BETWEEN '1990-01-01' AND '2000-12-31'
GROUP BY NAME;
