SELECT FROM ANIMALS WHERE NAME LIKE '%MON%';
SELECT NAME FROM ANIMALS WHERE DATE_OF_BIRTH::DATE >= '2016-01-01' AND DATE_OF_BIRTH::DATE <='2019-12-31';
SELECT NAME FROM ANIMALS WHERE NEUTERED = TRUE AND  ESCAPE_ATTEMPTS < 3;
SELECT DATE_OF_BIRTH FROM ANIMALS WHERE NAME='AGUMON' OR NAME= 'PIKACHU';
SELECT NAME, ESCAPE_ATTEMPTS FROM ANIMALS WHERE WEIGHT_KG > 10.5;
SELECT * FROM ANIMALS WHERE NEUTERED = TRUE;
SELECT * FROM ANIMALS WHERE NAME <> 'Gabumon';
SELECT * FROM ANIMALS WHERE WEIGHT_KG >=10.4 OR WEIGHT_KG <= 17.3;