CREATE TABLE animals(ID BIGSERIAL PRIMARY KEY NOT NULL,
NAME VARCHAR(30) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
ESCAPE_ATTEMPTS INT NOT NULL,
NEUTERED BOOLEAN NOT NULL,
WEIGHT_KG FLOAT NOT NULL);

ALTER TABLE ANIMALS
ADD SPECIES TEXT;




