CREATE TABLE animals(ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
NAME VARCHAR(30) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
ESCAPE_ATTEMPTS INT NOT NULL,
NEUTERED BOOLEAN NOT NULL,
WEIGHT_KG FLOAT NOT NULL);